### ISSUE TITLE
Unable to open thread or post after DNN9.2.2 upgrade

### ISSUE THREAD

**Issue by PascalIcatt** [DNNCommunity/DNN.Forum#19]
After installing DNN9.2.2 we get the following error and stacktrace in our logs after trying to open a thread:

Message:Object reference not set to an instance of an object.

StackTrace:

InnerMessage:Object reference not set to an instance of an object.

InnerStackTrace:

at DotNetNuke.Modules.Forum.Posts.RenderPostAuthor(HtmlTextWriter wr, PostInfo Post, Boolean PostCountIsEven) at DotNetNuke.Modules.Forum.Posts.RenderPost(HtmlTextWriter wr, PostInfo Post, Boolean PostCountIsEven) at DotNetNuke.Modules.Forum.Posts.RenderPosts(HtmlTextWriter wr) at DotNetNuke.Modules.Forum.Posts.RenderThread(HtmlTextWriter wr) at DotNetNuke.Modules.Forum.Posts.Render(HtmlTextWriter wr) at DotNetNuke.Modules.Forum.ForumBaseControl.Render(HtmlTextWriter wr) at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) at System.Web.UI.UpdatePanel.RenderChildren(HtmlTextWriter writer) at System.Web.UI.UpdatePanel.Render(HtmlTextWriter writer) at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) at DotNetNuke.UI.Modules.ModuleHost.RenderContents(HtmlTextWriter writer) at System.Web.UI.WebControls.WebControl.Render(HtmlTextWriter writer) at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) at System.Web.UI.HtmlControls.HtmlContainerControl.Render(HtmlTextWriter writer) at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) at System.Web.UI.HtmlControls.HtmlContainerControl.Render(HtmlTextWriter writer) at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) at System.Web.UI.HtmlControls.HtmlContainerControl.Render(HtmlTextWriter writer) at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) at ASP.portals__default_skins_jongenout_one_col_ascx.__Render__control1(HtmlTextWriter __w, Control parameterContainer) at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) at System.Web.UI.HtmlControls.HtmlForm.RenderChildren(HtmlTextWriter writer) at System.Web.UI.HtmlControls.HtmlContainerControl.Render(HtmlTextWriter writer) at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) at System.Web.UI.HtmlControls.HtmlForm.RenderControl(HtmlTextWriter writer) at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) at System.Web.UI.HtmlControls.HtmlContainerControl.Render(HtmlTextWriter writer) at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) at DotNetNuke.Framework.PageBase.Render(HtmlTextWriter writer) at DotNetNuke.Framework.DefaultPage.Render(HtmlTextWriter writer) at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by juvander** [comment]
Which forum version?

**Comment by PascalIcatt** [comment]
My apologies, we are using the latest version of the module: 05.01.00

**Comment by juvander** [comment]
Are you using the one updated 10/23?

**Comment by PascalIcatt** [comment]
Yes, that's the one we are using.

**Comment by juvander** [comment]
Any special settings? Online users, external profile, avatars?

I just upgraded my own site few weeks back to 9.2.2 and there it is working just fine, so must be now some setting that is causing this.

**Comment by Huib-W** [comment]
We're having the same issue on our end. We're unable to open a thread on DNN 9.2.2. This is the admin log message: 

`Message:Object reference not set to an instance of an object.
StackTrace:
InnerMessage:Object reference not set to an instance of an object.
InnerStackTrace:
at DotNetNuke.Modules.Forum.Posts.RenderPostAuthor(HtmlTextWriter wr, PostInfo Post, Boolean PostCountIsEven) at DotNetNuke.Modules.Forum.Posts.RenderPost(HtmlTextWriter wr, PostInfo Post, Boolean PostCountIsEven) at DotNetNuke.Modules.Forum.Posts.RenderPosts(HtmlTextWriter wr) at DotNetNuke.Modules.Forum.Posts.RenderThread(HtmlTextWriter wr) at DotNetNuke.Modules.Forum.Posts.Render(HtmlTextWriter wr) at DotNetNuke.Modules.Forum.ForumBaseControl.Render(HtmlTextWriter wr) at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) at System.Web.UI.UpdatePanel.RenderChildren(HtmlTextWriter writer) at System.Web.UI.UpdatePanel.Render(HtmlTextWriter writer) at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) at DotNetNuke.UI.Modules.ModuleHost.RenderContents(HtmlTextWriter writer) at System.Web.UI.WebControls.WebControl.Render(HtmlTextWriter writer) at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) at System.Web.UI.HtmlControls.HtmlContainerControl.Render(HtmlTextWriter writer) at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) at System.Web.UI.HtmlControls.HtmlContainerControl.Render(HtmlTextWriter writer) at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) at System.Web.UI.HtmlControls.HtmlContainerControl.Render(HtmlTextWriter writer) at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) at ASP.portals__default_skins_**removed due to privacy**_one_col_ascx.__Render__control1(HtmlTextWriter __w, Control parameterContainer) at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) at System.Web.UI.HtmlControls.HtmlForm.RenderChildren(HtmlTextWriter writer) at System.Web.UI.HtmlControls.HtmlContainerControl.Render(HtmlTextWriter writer) at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) at System.Web.UI.HtmlControls.HtmlForm.RenderControl(HtmlTextWriter writer) at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) at System.Web.UI.HtmlControls.HtmlContainerControl.Render(HtmlTextWriter writer) at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) at DotNetNuke.Framework.PageBase.Render(HtmlTextWriter writer) at DotNetNuke.Framework.DefaultPage.Render(HtmlTextWriter writer) at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)`
Which looks very similar to the original poster's error message. We've also recently updated our Forum software (to 05.01.00) in an attempt to solve the issue, however it hasn't helped. 

I don't think we use any special settings. I think it might has something to do with missing profile fields however I might be completely in the wrong there.

**Comment by juvander** [comment]
Put these into bin -directory, DotNetNuke.Modules.Forum.dll should replace the existing one and then adding this .pdb.

Then see the error log in more detail if it give the source line number from where the exception comes from.

[Archive.zip](https://github.com/DNNCommunity/DNN.Forum/files/2668722/Archive.zip)

**Comment by Huib-W** [comment]
Thanks for your very quick reply! We'll get our teams on that right away! Just to provide a bit more information, this is the error message we get when we try to open a topic, which looks like it could provide more useful information:
`Message:Value cannot be null. Parameter name: source
StackTrace:
InnerMessage:Value cannot be null. Parameter name: source
InnerStackTrace:
at System.Linq.Enumerable.Any[TSource](IEnumerable 1 source, Func 2 predicate) at DNNConnect.CKEditorProvider.Utilities.SettingsUtil.CheckSettingsExistByKey(List 1 editorHostSettings, String key) at DNNConnect.CKEditorProvider.Web.EditorControl.LoadAllSettings() at DNNConnect.CKEditorProvider.Web.EditorControl.CKEditorInit(Object sender, EventArgs e) at System.Web.UI.Control.OnInit(EventArgs e) at System.Web.UI.Control.InitRecursive(Control namingContainer) at System.Web.UI.Control.AddedControl(Control control, Int32 index) at DotNetNuke.UI.UserControls.TextEditor.OnLoad(EventArgs e)`

**Comment by juvander** [comment]
This I believe is something else as it states CKEditorProvider as source for error.

**Comment by Huib-W** [comment]
Hmm, my bad! Guess we'll look into that as well. Thank you very much for your assistance here. We'll report back as soon as we have more information.

**Comment by juvander** [comment]
Jep, lets hope this .pdb would give the line number where this happens.

**Comment by PascalIcatt** [comment]
Thank you for the quick response juvander.
We have replaced the dll and added the pdb.
We get a new log message indeed:

Message:Object reference not set to an instance of an object.

StackTrace:

InnerMessage:Object reference not set to an instance of an object.

InnerStackTrace:

at DotNetNuke.Modules.Forum.Posts.RenderPostAuthor(HtmlTextWriter wr, PostInfo Post, Boolean PostCountIsEven) in C:\agent\_work\11\s\branches\DNN_5\Components\UI\Posts.vb:line 1953 at DotNetNuke.Modules.Forum.Posts.RenderPost(HtmlTextWriter wr, PostInfo Post, Boolean PostCountIsEven) in C:\agent\_work\11\s\branches\DNN_5\Components\UI\Posts.vb:line 1776 at DotNetNuke.Modules.Forum.Posts.RenderPosts(HtmlTextWriter wr) in C:\agent\_work\11\s\branches\DNN_5\Components\UI\Posts.vb:line 1634 at DotNetNuke.Modules.Forum.Posts.RenderThread(HtmlTextWriter wr) in C:\agent\_work\11\s\branches\DNN_5\Components\UI\Posts.vb:line 1457 at DotNetNuke.Modules.Forum.Posts.Render(HtmlTextWriter wr) in C:\agent\_work\11\s\branches\DNN_5\Components\UI\Posts.vb:line 821 at DotNetNuke.Modules.Forum.ForumBaseControl.Render(HtmlTextWriter wr) in C:\agent\_work\11\s\branches\DNN_5\Components\BaseControl\BaseControl.vb:line 127 at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) at System.Web.UI.UpdatePanel.RenderChildren(HtmlTextWriter writer) at System.Web.UI.UpdatePanel.Render(HtmlTextWriter writer) at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) at DotNetNuke.UI.Modules.ModuleHost.RenderContents(HtmlTextWriter writer) at System.Web.UI.WebControls.WebControl.Render(HtmlTextWriter writer) at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) at System.Web.UI.HtmlControls.HtmlContainerControl.Render(HtmlTextWriter writer) at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) at System.Web.UI.HtmlControls.HtmlContainerControl.Render(HtmlTextWriter writer) at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) at System.Web.UI.HtmlControls.HtmlContainerControl.Render(HtmlTextWriter writer) at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) at ASP.portals__default_skins_jongenout_one_col_ascx.__Render__control1(HtmlTextWriter __w, Control parameterContainer) at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) at System.Web.UI.HtmlControls.HtmlForm.RenderChildren(HtmlTextWriter writer) at System.Web.UI.HtmlControls.HtmlContainerControl.Render(HtmlTextWriter writer) at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) at System.Web.UI.HtmlControls.HtmlForm.RenderControl(HtmlTextWriter writer) at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) at System.Web.UI.HtmlControls.HtmlContainerControl.Render(HtmlTextWriter writer) at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) at DotNetNuke.Framework.PageBase.Render(HtmlTextWriter writer) at DotNetNuke.Framework.DefaultPage.Render(HtmlTextWriter writer) at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by juvander** [comment]
Hmm - was not helping that much. Point where it now throws this exception is not something that it possibly could do that... You did copy the .dll there as well, not just the pdb -file?

**Comment by PascalIcatt** [comment]
Yes, I copied both files and then restarted the application (by changing the web.config)

**Comment by juvander** [comment]
Ok, will see if I can some more logging to catch what it is really doing, will get back to this.

**Comment by juvander** [comment]
Which theme are you using?

**Comment by juvander** [comment]
Is this site public somewhere to take a look?

**Comment by PascalIcatt** [comment]
We are using a custom made theme. I also reverted back to the default themes, likegravity and xcillion, but the same issues.
Unfortunately it's a closed off site for a protected community.
Giving you access is therefor not possible.

**Comment by juvander** [comment]
Does this affect all threads or just some? How about creating totally new one?

Also, check the forum theme, is that the default one or have you customized that one as well?

**Comment by PascalIcatt** [comment]
It affects all treads. I can create a new thread and open it, but existing threads i cannot open.
Besides the DNN site theme, we haven't changed any forum theming

**Comment by juvander** [comment]
Just be sure: New thread you created can be opened just fine? And ones created before not?

**Comment by PascalIcatt** [comment]
Yes, that is correct

**Comment by juvander** [comment]
What forum version you had before upgrading to 9.2.2? Sounds like something is now messed up in the database for old threads.

**Comment by PascalIcatt** [comment]
We were running 05.00.06 on DNN 8.0.4

**Comment by juvander** [comment]
Anything special during upgrade? I did the upgrade from DNN 8.0.4 just few weeks back to 9.2.2 and don't experience this. 

Have you deleted users lately?

**Comment by PascalIcatt** [comment]
Nope, nothing special. We have also updated the another NN instance to 9.2.2 and installed the forum on there and we didnt experience any issues at all. only this host has these problms.
I'll discuss internally if we can strip the host and give you access, but I'm not sure if that's possible.

**Comment by juvander** [comment]
You might also take a look at the database that there are those forum tables and data on them.
