### ISSUE TITLE
Installing 5.00.05

### ISSUE THREAD

**Issue by JaySMa** [DNNCommunity/DNN.Forum#2]
Downloaded the 5.00.05 zip file.  On our development box (DNN v7.4.1), tried installing/updating from 5.00.03.  In the pop-up box, got a 500 internal server error.  Within the event logs, it reports:

Message:Maximum request length exceeded.
StackTrace:
InnerMessage:Maximum request length exceeded.
InnerStackTrace:
   at System.Web.HttpRequest.GetEntireRawContent()
   at System.Web.HttpRequest.GetMultipartContent()
   at System.Web.HttpRequest.FillInFormCollection()
   at System.Web.HttpRequest.EnsureForm()
   at System.Web.HttpRequest.get_HasForm()
   at System.Web.UI.Page.GetCollectionBasedOnMethod(Boolean dontReturnNull)
   at System.Web.UI.Page.DeterminePostBackMode()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by juvander** [comment]
See if this is the issue: http://www.dnnsoftware.com/forums/threadid/270951/scope/posts/maximum-request-length-exceeded-error

**Comment by JaySMa** [comment]
Dang, forgot about that; that's what it was.  Sorry about that.

**Comment by JaySMa** [comment]
Got a different issue now; sorry.  When i look in this temp install directory, it shows a README.md file and a branches folder.

Message:Could not find file 'C:\Website\DNNCE\Install\Temp\rcnazp43\License.txt'.
StackTrace:
InnerMessage:Could not find file 'C:\Website\DNNCE\Install\Temp\rcnazp43\License.txt'.
InnerStackTrace:
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Boolean detectEncodingFromByteOrderMarks)
   at System.IO.File.OpenText(String path)
   at DotNetNuke.Common.Utilities.FileSystemUtils.ReadFile(String filePath)
   at DotNetNuke.Services.Installer.Installers.PackageInstaller.ReadTextFromFile(String source)
   at DotNetNuke.Services.Installer.Installers.PackageInstaller.ReadManifest(XPathNavigator manifestNav)
   at DotNetNuke.Services.Installer.Installer.ProcessPackages(XPathNavigator rootNav)
   at DotNetNuke.Services.Installer.Installer.ReadManifest(Boolean deleteTemp)
   at DotNetNuke.Modules.Admin.Extensions.Install.wizInstall_NextButtonClick(Object sender, WizardNavigationEventArgs e)
   at System.Web.UI.WebControls.Wizard.OnBubbleEvent(Object source, EventArgs e)
   at System.Web.UI.Control.RaiseBubbleEvent(Object source, EventArgs args)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by juvander** [comment]
Which file did you download?

**Comment by JaySMa** [comment]
On the main page, below Clone in Desktop, I clicked on the Download Zip button and it downloaded DotNetNuke-Forum-05.00.05.zip.

**Comment by juvander** [comment]
Take from here the install zip: https://github.com/juvander/DotNetNuke-Forum/releases/tag/05.00.04
You have downloaded just the sources now, not the installation zip.

**Comment by JaySMa** [comment]
Yea, that works fine.  Just a matter of my lack of familiarity with GitHub; now I understand how to get the latest release, etc.  Thanks again for your help..
