### ISSUE TITLE
DotNetNuke Lucene Search not working 'Lock obtain timed out' in load balanced env, how to fix?

### ISSUE THREAD

**Issue by Swimburger** [DNNCommunity/DNN.Forum#22]
We have a DNN site running on two servers that are load balanced. To ensure the files are in sync on these servers, we are using File Replication Service.

Search works fine on DNN when not load balanced, but in the load balanced setup the search stops working after a while (no suggestions, no results).
The following related exception is all over our log files:

```
[D:2][T:31][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Lucene.Net.Store.LockObtainFailedException: Lock obtain timed out: NativeFSLock@D:\Sites\SiteName\App_Data\Search\write.lock
   at Lucene.Net.Store.Lock.Obtain(Int64 lockWaitTimeout)
   at Lucene.Net.Index.IndexWriter.Init(Directory d, Analyzer a, Boolean create, IndexDeletionPolicy deletionPolicy, Int32 maxFieldLength, IndexingChain indexingChain, IndexCommit commit)
   at Lucene.Net.Index.IndexWriter..ctor(Directory d, Analyzer a, MaxFieldLength mfl)
   at DotNetNuke.Services.Search.Internals.LuceneControllerImpl.get_Writer()
   at DotNetNuke.Services.Search.Internals.LuceneControllerImpl.Delete(Query query)
   at DotNetNuke.Services.Search.Internals.InternalSearchControllerImpl.DeleteSearchDocumentInternal(SearchDocument searchDocument, Boolean autoCommit)
   at DotNetNuke.Services.Search.Internals.InternalSearchControllerImpl.DeleteSearchDocumentsByModule(Int32 portalId, Int32 moduleId, Int32 moduleDefId)
   at DotNetNuke.Services.Search.SearchDataStore.StoreSearchItems(SearchItemInfoCollection searchItems)
   at DotNetNuke.Services.Search.SearchEngine.IndexContent()
   at DotNetNuke.Services.Search.SearchEngineScheduler.DoWork()
```
My best guess is that the issue is caused because both servers are running their search functionality, and the File Replication Service is syncing the files which causes conflicts.
What would be the best way to solve this?

- Add an exclusion rule to not replicate the search index folder, but let both servers keep running search?
- Somehow disable one server from indexing?
- Any other suggestions?

Installation details:
DNN v. 09.02.00 (366)
.NET Framework 4.6

**Comment by Swimburger** [comment]
Question has been asked on StackOverflow as well: https://stackoverflow.com/questions/54577226/dotnetnuke-lucene-search-not-working-lock-obtain-timed-out-in-load-balanced-en

**Comment by juvander** [comment]
Nothing to do with DNN.Forum module

**Comment by Swimburger** [comment]
I misread a post on DNN forum that this was the new forum to post questions for overall DNN stuff. Thanks for pointing that out. You can completely delete this if you can.
