### ISSUE TITLE
Error message on clicking Report button

### ISSUE THREAD

**Issue by nunotv** [DNNCommunity/DNN.Forum#3]
Hi

On a test installation of DNN Forum I get an error message on pressing report button:  
"A critical error has occurred. Please check Event Viewer for further details."

On Event Viewer I can find 3 entries: 

**ENTRY 1**
AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:1466b571-880f-4d3a-aa95-100059f8e9a3
AssemblyVersion:8.0.0
PortalId:0
UserId:1
TabId:116
RawUrl:/Forum/ctl/PostReport/mid/471/postid/4
Referrer:http://www.topick.pt/Forum/forumid/3/threadid/3/scope/posts
UserAgent:Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36
ExceptionHash:3Ghp99Ju8sgIQg+zU5Gn7w==
Message:Control with ID 'cmdCancel' being registered through RegisterAsyncPostBackControl or RegisterPostBackControl must implement either INamingContainer, IPostBackDataHandler, or IPostBackEventHandler.
StackTrace:
InnerMessage:Control with ID 'cmdCancel' being registered through RegisterAsyncPostBackControl or RegisterPostBackControl must implement either INamingContainer, IPostBackDataHandler, or IPostBackEventHandler.
InnerStackTrace:
   at System.Web.UI.PageRequestManager.RegisterPostBackControl(Control control)
   at DotNetNuke.Framework.AJAX.RegisterPostBackControl(Control objControl)
   at DotNetNuke.Modules.Forum.PostReport.Page_Init(Object sender, EventArgs e)
   at System.Web.UI.Control.OnInit(EventArgs e)
   at DotNetNuke.Entities.Modules.PortalModuleBase.OnInit(EventArgs e)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.AddedControl(Control control, Int32 index)
   at System.Web.UI.Control.EnsureChildControls()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
Source:
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
Server Name:

**ENTRY 2**
AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:904adcac-3ad0-493d-bcfe-b11d3b0c4a41
AssemblyVersion:
PortalId:-1
UserId:-1
TabId:-1
RawUrl:
Referrer:
UserAgent:
ExceptionHash:y5qhQyGtBVR9ujG7syLqTg==
Message:Unhandled Error Adding Module to contentPane.
StackTrace:
   at DotNetNuke.UI.Skins.Pane.InjectModule(ModuleInfo module)
   at DotNetNuke.UI.Skins.Skin.InjectModule(Pane pane, ModuleInfo module)
InnerMessage:Control with ID 'cmdCancel' being registered through RegisterAsyncPostBackControl or RegisterPostBackControl must implement either INamingContainer, IPostBackDataHandler, or IPostBackEventHandler.
InnerStackTrace:
   at System.Web.UI.PageRequestManager.RegisterPostBackControl(Control control)
   at DotNetNuke.Framework.AJAX.RegisterPostBackControl(Control objControl)
   at DotNetNuke.Modules.Forum.PostReport.Page_Init(Object sender, EventArgs e)
   at System.Web.UI.Control.OnInit(EventArgs e)
   at DotNetNuke.Entities.Modules.PortalModuleBase.OnInit(EventArgs e)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.AddedControl(Control control, Int32 index)
   at System.Web.UI.Control.EnsureChildControls()
   at DotNetNuke.UI.Containers.Container.get_ModuleControl()
   at DotNetNuke.UI.Containers.Container.ProcessModule()
   at DotNetNuke.UI.Skins.Pane.InjectModule(ModuleInfo module)
Source:DotNetNuke
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
Server Name: 

**ENTRY 3**
AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:b71b58cf-525f-4940-9682-04fc135d77bb
AssemblyVersion:
PortalId:-1
UserId:-1
TabId:-1
RawUrl:
Referrer:
UserAgent:
ExceptionHash:nFEOfh+9qUciteQEFEeEuw==
Message:Control with ID 'cmdCancel' being registered through RegisterAsyncPostBackControl or RegisterPostBackControl must implement either INamingContainer, IPostBackDataHandler, or IPostBackEventHandler.
StackTrace:
   at System.Web.UI.PageRequestManager.RegisterPostBackControl(Control control)
   at DotNetNuke.Framework.AJAX.RegisterPostBackControl(Control objControl)
   at DotNetNuke.Modules.Forum.PostReport.Page_Init(Object sender, EventArgs e)
   at System.Web.UI.Control.OnInit(EventArgs e)
   at DotNetNuke.Entities.Modules.PortalModuleBase.OnInit(EventArgs e)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.AddedControl(Control control, Int32 index)
   at System.Web.UI.Control.EnsureChildControls()
   at DotNetNuke.UI.Containers.Container.get_ModuleControl()
   at DotNetNuke.UI.Containers.Container.ProcessModule()
   at DotNetNuke.UI.Skins.Pane.InjectModule(ModuleInfo module)
InnerMessage:
InnerStackTrace:
Source:System.Web.Extensions
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
Server Name:

The forum module is on a page with Page Culture = Neutral Culture    

**Environment:**
DNN Forum version: 5.0.6
DNN version:  08.00.00 (809)
Windows 2008 R2

Can anyone give me help on this issue?

Best regards

NTV

**Comment by juvander** [comment]
Download the setup again and reinstall.

**Comment by nunotv** [comment]
Thank you Juvander. Tests after reinstallation where successful.

Regards
NTV
