### ISSUE TITLE
Settings required to upload images

### ISSUE THREAD

**Issue by tonyatl2** [DNNCommunity/DNN.Forum#34]
I am evaluating active forums 6.5 on dnn 9.8.1. i was trying to create a message with an image attachment (jpg), but active forums won't let me upload it. there is an error 405. what do i need to configure to allow uploading of images?

**Comment by tonyatl2** [comment]
i found that active forums maintains its own list of allowed file types. i thought it might have been using site settings. adding jpg to the list solved the problem.

however, once i uploaded the image, i clicked to view it from the forums posting. i got a run time sql error:

AbsoluteURL:/DesktopModules/ActiveForums/viewer.aspx

DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke

ExceptionGUID:0597133b-afbe-4007-abad-ac6b68f2c577

AssemblyVersion:9.8.1

PortalId:0

UserId:1

TabId:22

RawUrl:/DesktopModules/ActiveForums/viewer.aspx?portalid=0&amp;moduleid=409&amp;attachmentid=1

Referrer:https://www.etiquemarket.com/forums/aft/1

UserAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36

ExceptionHash:/VFfOZMMg9MveQQqJsZTO0DUn/8=

Message:Invalid object name 'dbo.vw_activeforums_TopicView as tv on tv.ContentId = A.ContentId INNER JOIN dbo.[activeforums_ForumTopics'.

StackTrace:

InnerMessage:Invalid object name 'dbo.vw_activeforums_TopicView as tv on tv.ContentId = A.ContentId INNER JOIN dbo.[activeforums_ForumTopics'.

InnerStackTrace:

   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.ApplicationBlocks.Data.SqlHelper.ExecuteReader(SqlConnection connection, SqlTransaction transaction, CommandType commandType, String commandText, SqlParameter[] commandParameters, SqlConnectionOwnership connectionOwnership)
   at Microsoft.ApplicationBlocks.Data.SqlHelper.ExecuteReader(String connectionString, CommandType commandType, String commandText, SqlParameter[] commandParameters)
   at Microsoft.ApplicationBlocks.Data.SqlHelper.ExecuteReader(String connectionString, String spName, Object[] parameterValues)
   at DotNetNuke.Modules.ActiveForums.Data.AttachController.Get(Int32 attachmentId, Int32 fileId, Boolean withSecurity)
   at DotNetNuke.Modules.ActiveForums.af_viewer.OnLoad(EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
Source:

FileName:

FileLineNumber:0

FileColumnNumber:0

Method:

**Comment by tonyatl2** [comment]
then, when i tried to delete the topic, this error:

js:112 POST https://www.etiquemarket.com/desktopmodules/activeforums/handlers/forumhelper.ashx?TabId=46&PortalId=0&moduleid=409&language=en-US 404
